---
- hosts: all
  become: true
  vars_files:
    - ../vars/default.yml

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        ports: 
          - "8080:80"
        state: started
        volumes: "/var/log/nginx:/var/log/nginx"
